### ISSUE TITLE
Move electron out of dependencies?

### ISSUE THREAD

**Issue by cmdcolin** [h3poteto/electron-mock-ipc#206]
Hi there

We use electron-mock-ipc and it's great. I was looking for ways to cut down on our node_modules size and I was wondering if electron is required to be a dependency? Could it be a peerDependency or even a devDependency?

It adds about 180MB to our node_modules folder to have it in the normal "dependencies" array

**Comment by h3poteto** [comment]
This package depends on Electron, for example: https://github.com/h3poteto/electron-mock-ipc/blob/2f543c0064fab58f27b4d8a0b3a62a860ba4521d/src/ipc-main.ts#L3

So I can't remote Electron from dependencies, and it is not "devDependency".

Generally, people use this library with Electron, because this package is not necessary if user don't use Electron. Why do you want to remove Electron from node_modules? If you remove it, will your application work?

**Comment by cmdcolin** [comment]
The thing I observe is in my codebase, I have two copies of electron downloaded in node_modules

One comes from electron-mock-ipc
One comes from my modules dependency on electron

![Screenshot from 2020-07-23 07-11-57](https://user-images.githubusercontent.com/6511937/88281133-24658000-ccb5-11ea-8500-59acd1d2bd8b.png)

It seems like maybe it could be a peerDependency in this case?

**Comment by h3poteto** [comment]
OK, I will try to move Electron to peerDependency.

**Comment by cmdcolin** [comment]
Thanks!

**Comment by cmdcolin** [comment]
Any chance to make a release with this added?

**Comment by h3poteto** [comment]
This change is already released: https://github.com/h3poteto/electron-mock-ipc/blob/master/package.json#L47

**Comment by h3poteto** [comment]
Oh, sorry I will release new version.

**Comment by h3poteto** [comment]
I'm sorry for being late, I released v0.3.8, so please use this.
https://www.npmjs.com/package/electron-mock-ipc/v/0.3.8

**Comment by cmdcolin** [comment]
No worries, thanks! :)
